### ISSUE TITLE
Exception in kivakit merged gRPC

### ISSUE THREAD

**Issue by haifeng-z** [Telenav/kivakit#110]
**Description**
When I call gRPC in safety service, it throws exception: java.lang.NoClassDefFoundError: kivakit/merged/grpc/io/perfmark/PerfMark.

**Reproduce Case**
When call gRPC service via BlockingStub, exception will be thrown.

MapMatchingServiceGrpc.MapMatchingServiceBlockingStub graphStub = MapMatchingServiceGrpc.newBlockingStub(channel);
……
MatchingResponse response = graphStub.match(matchingRequest.build()); 

**Stack Trace**
[main] INFO kivakit.merged.grpc.io.netty.util.internal.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
May 05, 2022 11:15:54 PM io.grpc.stub.ClientCalls$ThreadlessExecutor waitAndDrain
WARNING: Runnable threw exception
java.lang.NoClassDefFoundError: kivakit/merged/grpc/io/perfmark/PerfMark
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.ClientCallImpl.<init>(ClientCallImpl.java:105)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.ManagedChannelImpl$RealChannel$1.newCall(ManagedChannelImpl.java:955)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.ManagedChannelImpl$RealChannel.newClientCall(ManagedChannelImpl.java:1144)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.ManagedChannelImpl$RealChannel.access$4500(ManagedChannelImpl.java:936)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.ManagedChannelImpl$RealChannel$PendingCall$1.run(ManagedChannelImpl.java:1106)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:740)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149)
                at safety.service.microservice/com.telenav.cloud.mapgraph.grpc.v2.mapmatching.MapMatchingServiceGrpc$MapMatchingServiceBlockingStub.match(MapMatchingServiceGrpc.java:135)
                at safety.service.microservice/com.telenav.scout.safety.service.api.driving.safety.MatchingProxy.main(MatchingProxy.java:36)
Caused by: java.lang.ClassNotFoundException: kivakit.merged.grpc.io.perfmark.PerfMark
                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
                at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
                ... 9 more
 
May 06, 2022 9:49:36 AM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<1>: (graph-service-tn-osm-na.stg.k8s.mypna.com:9081)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host graph-service-tn-osm-na.stg.k8s.mypna.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: graph-service-tn-osm-na.stg.k8s.mypna.com: nodename nor servname provided, or not known
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
                at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.net.UnknownHostException: graph-service-tn-osm-na.stg.k8s.mypna.com: nodename nor servname provided, or not known
                at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
                at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932)
                at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517)
                at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851)
                at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1507)
                at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1366)
                at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1300)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
                ... 5 more
}
May 06, 2022 9:49:37 AM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<1>: (graph-service-tn-osm-na.stg.k8s.mypna.com:9081)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host graph-service-tn-osm-na.stg.k8s.mypna.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: graph-service-tn-osm-na.stg.k8s.mypna.com
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
                at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.net.UnknownHostException: graph-service-tn-osm-na.stg.k8s.mypna.com
                at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:800)
                at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1507)
                at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1366)
                at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1300)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
                at [kivakit.merged.grpc@1.5.0](mailto:kivakit.merged.grpc@1.5.0)/io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
                ... 5 more
}

**Comment by jonathanl-telenav** [comment]
this should have been fixed by kivakit 1.6.2 release. please reopen if not.
